# Generated by Django 4.2.9 on 2025-03-25 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_is_collector_customuser_is_tourist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='beach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collectors', to='core.beach'),
        ),
    ]
