# Generated by Django 4.2.9 on 2025-03-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_collector_beach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collector',
            name='qr_code',
        ),
    ]
