# Generated by Django 4.2.9 on 2025-03-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_collector_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collector',
            name='beach',
        ),
        migrations.AddField(
            model_name='collector',
            name='beaches',
            field=models.ManyToManyField(blank=True, related_name='collectors', to='core.beach'),
        ),
    ]
