# Generated by Django 4.2.9 on 2025-03-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_collector_beaches_collector_beach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collector',
            name='beach',
        ),
    ]
